#!/bin/sh /etc/rc.common                                                                                                         
                                                                                                                                 
NAME='shairport-sync'                                                                                                            
START=99                                                                                                                         
                                                                                                                                 
#shairport-sync is always daemonized here                                                                                        
                                                                                                                                 
handle_shairport_sync() {                                                                                                        
        local config="$1"                                                                                                        
        local custom="$2"                                                                                                        
        local name                                                                                                               
        local port                                                                                                               
        local airplaylatency                                                                                                     
        local ituneslatency                                                                                                      
        local stuffing                                                                                                           
        local awaitactioncompletion                                                                                              
        local device                                                                                                             
        local devicetype                                                                                                         
        local volumecontrolname                                                                                                  
        local beforeaction                                                                                                       
        local afteraction                                                                                                        
        config_get name "$1" name ""                                                                                             
        config_get port "$1" port ""                                                                                             
        config_get airplaylatency "$1" airplaylatency ""                                                                         
        config_get ituneslatency "$1" ituneslatency ""                                                                           
        config_get stuffing "$1" stuffing ""                                                                                     
        config_get awaitactioncompletion "$1" awaitactioncompletion ""                                                           
        config_get device "$1" device ""                                                                                         
        config_get devicetype "$1" devicetype ""                                                                                 
        config_get volumecontrolname "$1" volumecontrolname ""                                                                   
        config_get beforeaction "$1" beforeaction ""                                                                             
        config_get afteraction "$1" afteraction ""                                                                               
                                                                                                                                 
        # all this assumes that the only syntactically awkward parameter is the name, so we treat it differently                 
        arglist=""                                                                                                               
        [ -z "$port" ] || arglist="$arglist -p $port"                                                                            
        [ -z "$airplaylatency" ] || arglist="$arglist -A $airplaylatency"                                                        
        [ -z "$ituneslatency" ] || arglist="$arglist -i $ituneslatency"                                                          
        if [ -n "$stuffing" ] ; then                                                                                             
                case "x$stuffing" in                                                                                             
                        ( "xbasic" ) arglist="$arglist -S basic" ;;                                                              
                        ( "xsoxr" ) arglist="$arglist -S soxr" ;;                                                                
                        ( * ) logger "bad argument for -S option -- should be \"basic\" or \"soxr\"" ;;                          
                esac                                                                                                             
        fi                                                                                                                       
                                                                                                                                 
        # assuming beforeaction and afteraction are single-word commands, with no arguments, etc.                                
        [ -z "$beforeaction" ] || arglist="$arglist -B $beforeaction"                                                            
        [ -z "$afteraction" ] || arglist="$arglist -E $afteraction"                                                              
        if [ -n "$awaitactioncompletion" ] ; then                                                                                
                case "x$awaitactioncompletion" in                                                                                
                        ( "xtrue" ) arglist="$arglist -w " ;;                                                                    
                        ( "xfalse" ) ;;                                                                                          
                        ( * ) logger "bad choice for awaitactioncompletion -- should be \"true\" or \"false\"" ;;                
                esac                                                                                                             
        fi                                                                                                                       
                                                                                                                                 
        belist=""                                                                                                                
        [ -z "$device" ] || belist="$belist -d $device"                                                                          
        [ -z "$devicetype" ] || belist="$belist -t $devicetype"                                                                  
        [ -z "$volumecontrolname" ] || belist="$belist -c $volumecontrolname"                                                    
        [ -z "$belist" ] || belist=" --$belist"                                                                                  
                                                                                                                                 
        #echo "Arguments: arglist: \"$arglist\", belist: \"$belist\""                                                            
                                                                                                                                 
        if [ "x$name" = "x" ] ; then                                                                                             
                shairport-sync -d $arglist $belist                                                                               
        else                                                                                                                     
                shairport-sync -d -a "$name" $arglist $belist                                                                    
        fi                                                                                                                       
}                                                                                                                                
                                                                                                                                 
start() {                                                                                                                        
        config_load 'shairport-sync'                                                                                             
                                                                                                                                 
#hmm -- only one copy of shairport-sync can be running.                                                                          
#so this is not quite right...                                                                                                   
        config_foreach handle_shairport_sync 'shairport-sync'                                                                    
}                                                                                                                                
                                                                                                                                 
stop() {                                                                                                                         
        shairport-sync -k                                                                                                        
}                                                                                                                                

