#!/bin/sh /etc/rc.common                                                                                                         
                                                                                                                                 
NAME='shairport-sync'                                                                                                            
START=99                                                                                                                         
                                                                                                                                 
                                                                                                                                 
start() {  
# All settings are made in /etc/shairport-sync.conf. There's an up-to-date /etc/shairport-sync.conf.sample.                                                                                                                      
        shairport-sync -d                                                                                            
}                                                                                                                                
                                                                                                                                 
stop() {                                                                                                                         
        shairport-sync -k                                                                                                        
}                                                                                                                                

